spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gstMatchService
          uri: lb://gstMatchService
          predicates:
            - Path=/api/**